/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import controller.InvoiceController;
import javax.swing.table.DefaultTableModel;
import model.BDConnection;
import model.Client;
import model.Invoice;

/**
 *
 * @author Estudiante
 */
public class MainModule extends javax.swing.JFrame {

    ClientController cliController;
    InvoiceController invController;
    DefaultTableModel tableModel;
    DefaultTableModel tableInvoiceModel;
    boolean updateFlag;
    int tablePos;

    /**
     * Creates new form ClientModule
     */
    public MainModule() {
        initComponents();

        //Starts new BD connection
        BDConnection connection = new BDConnection();
        cliController = new ClientController(connection);
        invController = new InvoiceController(connection);

        //Checks if the query was succesfully executed
        if (!cliController.index()) {
            System.out.println("No se ejecuto la consulta");
        }

        //Client table configuration
        String[] columnNames = new String[]{"ID", "Name", "Phone Number", "Address"};
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        clientTable.setModel(tableModel);
        refreshClientTable();

        //Checks if the query was succesfully executed
        if (!invController.index()) {
            System.out.println("No se ejecuto la consulta");
        }
        
        //Invoice table configuration
        String[] columnInvoiceNames = new String[]{"ID", "Fecha", "Cliente"};
        tableInvoiceModel = new DefaultTableModel();
        tableInvoiceModel.setColumnIdentifiers(columnInvoiceNames);
        invoiceTable.setModel(tableInvoiceModel);
        updateFlag = false;
        refreshClientTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoMessage = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        clientIDTxt = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clientPhoneTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        clientAddressTxt = new javax.swing.JTextField();
        clientNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        invoicetIDTxt = new javax.swing.JTextField();
        removeInvoiceBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        invoiceTotalTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        invoiceDateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        clientListCbx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName(""); // NOI18N

        clientIDTxt.setToolTipText("Escribe aquí el ID");

        removeBtn.setText("Eliminar");
        removeBtn.setEnabled(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Clientes Registrados");

        clientPhoneTxt.setToolTipText("Escribe aquí el teléfono");

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        clientAddressTxt.setToolTipText("Escribe aquí la dirección");

        clientNameTxt.setToolTipText("Escribe aquí el nombre");

        jLabel1.setText("Módulo de clientes");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clientPhoneTxt)
                                    .addComponent(clientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(clientNameTxt)
                                    .addComponent(clientAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jButton1)
                                .addGap(27, 27, 27)
                                .addComponent(removeBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(removeBtn))
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Módulo de Clientes", jPanel1);

        invoicetIDTxt.setToolTipText("Escribe aquí el # de la factura");

        removeInvoiceBtn.setText("Eliminar");
        removeInvoiceBtn.setEnabled(false);
        removeInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInvoiceBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Facturas Registradas");

        invoiceTotalTxt.setToolTipText("Escribe aquí el valor total");

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        invoiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(invoiceTable);

        invoiceDateTxt.setToolTipText("Escribe aquí la fecha");

        jLabel4.setText("Módulo de Facturación");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        clientListCbx.setToolTipText("Selecciona el cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoiceTotalTxt)
                                    .addComponent(invoicetIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoiceDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(clientListCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jButton2)
                                .addGap(27, 27, 27)
                                .addComponent(removeInvoiceBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoicetIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientListCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(removeInvoiceBtn))
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Módulo de Facturación", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(infoMessage))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (invController.create(new Object[]{
            invoicetIDTxt.getText(),
            invoiceDateTxt.getText(),
            clientListCbx.getSelectedItem()
        })) {
            refreshInvoiceTable();
            clearInvoiceForm();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void invoiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceTableMouseClicked

    private void removeInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeInvoiceBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] params = new Object[4];
        params[Client.ID] = clientIDTxt.getText();
        params[Client.NAME] = clientNameTxt.getText();
        params[Client.PHONE_NUMBER] = clientPhoneTxt.getText();
        params[Client.ADDRESS] = clientAddressTxt.getText();
        if (updateFlag) {
            cliController.update(tablePos, params);
            refreshClientTable();

        } else {
            if (cliController.create(params)) {
                refreshClientTable();
            } else {
                infoMessage.setText("Parece que ha ocurrido un error :(");
            }
        }
        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked

        Client currentCLient = (Client) cliController.getObjectList().get(clientTable.getSelectedRow());
        clientIDTxt.setText(
                String.valueOf(currentCLient.getId())
        //String.valueOf(cliController.getObjectList().get(clientTable.getSelectedRow()).getId())
        );

        clientNameTxt.setText(
                ((Client) cliController.getObjectList().get(clientTable.getSelectedRow())).getName()
        );

        clientPhoneTxt.setText(
                ((Client) cliController.getObjectList().get(clientTable.getSelectedRow())).getPhoneNumber()
        );

        clientAddressTxt.setText(
                ((Client) cliController.getObjectList().get(clientTable.getSelectedRow())).getAddress()
        );

        updateFlag = true;
        tablePos = clientTable.getSelectedRow();
        jButton1.setText("Modificar");
        removeBtn.setEnabled(true);
    }//GEN-LAST:event_clientTableMouseClicked

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        if (cliController.delete(tablePos)) {
            refreshClientTable();
            clearForm();

        } else {
            infoMessage.setText("Ha ocurrido un error (Error: N14), por favor informa al soporte");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainModule().setVisible(true);
            }
        });
    }

    private void refreshClientTable() {
        try {
            tableModel.setRowCount(0);
            clientListCbx.removeAllItems();
            for (Object currentObject : cliController.getObjectList()) {
                Client currentClient = (Client) currentObject;
                //Adds current element to the table
                tableModel.addRow(new Object[]{currentClient.getId(), currentClient.getName(),
                    currentClient.getPhoneNumber(), currentClient.getAddress()});

                //Adds current object to combo boxe's list
                clientListCbx.addItem(currentClient);
            }
        } catch (Exception e) {
            infoMessage.setText("Error: " + e.getMessage());
        }

    }

    private void refreshInvoiceTable() {
        try {
            tableInvoiceModel.setRowCount(0);

            for (Object currentObject : invController.getObjectList()) {
                Invoice currentInvoice = (Invoice) currentObject;
                //Adds current element to the table
                tableInvoiceModel.addRow(new Object[]{currentInvoice.getId(), currentInvoice.getInvoiceDate(),
                    currentInvoice.getClient()});
            }
        } catch (Exception e) {
            infoMessage.setText("Error: " + e.getMessage());
        }

    }

    private void clearForm() {
        clientIDTxt.setText("");
        clientNameTxt.setText("");
        clientPhoneTxt.setText("");
        clientAddressTxt.setText("");
        jButton1.setText("Guardar");
        updateFlag = false;
        tablePos = -1;
        removeBtn.setEnabled(false);
    }

    private void clearInvoiceForm() {
        invoicetIDTxt.setText("");
        invoiceDateTxt.setText("");
        jButton2.setText("Guardar");
        updateFlag = false;
        tablePos = -1;
        removeInvoiceBtn.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientAddressTxt;
    private javax.swing.JTextField clientIDTxt;
    private javax.swing.JComboBox<Object> clientListCbx;
    private javax.swing.JTextField clientNameTxt;
    private javax.swing.JTextField clientPhoneTxt;
    private javax.swing.JTable clientTable;
    private javax.swing.JLabel infoMessage;
    private javax.swing.JTextField invoiceDateTxt;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JTextField invoiceTotalTxt;
    private javax.swing.JTextField invoicetIDTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton removeInvoiceBtn;
    // End of variables declaration//GEN-END:variables
}
