package pojo;
// Generated 16/04/2020 05:01:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Animal generated by hbm2java
 */
public class Animal  implements java.io.Serializable {


     private Integer idAnimal;
     private Address address;
     private MedicalTreatment medicalTreatment;
     private Person person;
     private boolean updateVaccines;
     private String name;
     private String age;
     private int species;
     private int breed;
     private int admissionDate;
     private Integer departureDate;
     private int animalType;
     private Set persons = new HashSet(0);
     private Set invoices = new HashSet(0);

    public Animal() {
    }

	
    public Animal(MedicalTreatment medicalTreatment, boolean updateVaccines, String age, int species, int breed, int admissionDate, int animalType) {
        this.medicalTreatment = medicalTreatment;
        this.updateVaccines = updateVaccines;
        this.age = age;
        this.species = species;
        this.breed = breed;
        this.admissionDate = admissionDate;
        this.animalType = animalType;
    }
    public Animal(Address address, MedicalTreatment medicalTreatment, Person person, boolean updateVaccines, String name, String age, int species, int breed, int admissionDate, Integer departureDate, int animalType, Set persons, Set invoices) {
       this.address = address;
       this.medicalTreatment = medicalTreatment;
       this.person = person;
       this.updateVaccines = updateVaccines;
       this.name = name;
       this.age = age;
       this.species = species;
       this.breed = breed;
       this.admissionDate = admissionDate;
       this.departureDate = departureDate;
       this.animalType = animalType;
       this.persons = persons;
       this.invoices = invoices;
    }
   
    public Integer getIdAnimal() {
        return this.idAnimal;
    }
    
    public void setIdAnimal(Integer idAnimal) {
        this.idAnimal = idAnimal;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public MedicalTreatment getMedicalTreatment() {
        return this.medicalTreatment;
    }
    
    public void setMedicalTreatment(MedicalTreatment medicalTreatment) {
        this.medicalTreatment = medicalTreatment;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public boolean isUpdateVaccines() {
        return this.updateVaccines;
    }
    
    public void setUpdateVaccines(boolean updateVaccines) {
        this.updateVaccines = updateVaccines;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public int getSpecies() {
        return this.species;
    }
    
    public void setSpecies(int species) {
        this.species = species;
    }
    public int getBreed() {
        return this.breed;
    }
    
    public void setBreed(int breed) {
        this.breed = breed;
    }
    public int getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(int admissionDate) {
        this.admissionDate = admissionDate;
    }
    public Integer getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Integer departureDate) {
        this.departureDate = departureDate;
    }
    public int getAnimalType() {
        return this.animalType;
    }
    
    public void setAnimalType(int animalType) {
        this.animalType = animalType;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


