package pojo;
// Generated 16/04/2020 05:01:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicine generated by hbm2java
 */
public class Medicine  implements java.io.Serializable {


     private Integer idMedicine;
     private int barcode;
     private String nameMedicine;
     private int quantityInWarehouse;
     private Date expirationDate;
     private String manufacturer;
     private Set medicalTreatments = new HashSet(0);

    public Medicine() {
    }

	
    public Medicine(int barcode, String nameMedicine, int quantityInWarehouse, Date expirationDate, String manufacturer) {
        this.barcode = barcode;
        this.nameMedicine = nameMedicine;
        this.quantityInWarehouse = quantityInWarehouse;
        this.expirationDate = expirationDate;
        this.manufacturer = manufacturer;
    }
    public Medicine(int barcode, String nameMedicine, int quantityInWarehouse, Date expirationDate, String manufacturer, Set medicalTreatments) {
       this.barcode = barcode;
       this.nameMedicine = nameMedicine;
       this.quantityInWarehouse = quantityInWarehouse;
       this.expirationDate = expirationDate;
       this.manufacturer = manufacturer;
       this.medicalTreatments = medicalTreatments;
    }
   
    public Integer getIdMedicine() {
        return this.idMedicine;
    }
    
    public void setIdMedicine(Integer idMedicine) {
        this.idMedicine = idMedicine;
    }
    public int getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(int barcode) {
        this.barcode = barcode;
    }
    public String getNameMedicine() {
        return this.nameMedicine;
    }
    
    public void setNameMedicine(String nameMedicine) {
        this.nameMedicine = nameMedicine;
    }
    public int getQuantityInWarehouse() {
        return this.quantityInWarehouse;
    }
    
    public void setQuantityInWarehouse(int quantityInWarehouse) {
        this.quantityInWarehouse = quantityInWarehouse;
    }
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public Set getMedicalTreatments() {
        return this.medicalTreatments;
    }
    
    public void setMedicalTreatments(Set medicalTreatments) {
        this.medicalTreatments = medicalTreatments;
    }




}


