package pojo;
// Generated Apr 3, 2020 9:23:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int barcode;
     private String name;
     private String description;
     private double sellPrice;
     private Set invoices = new HashSet(0);

    public Product() {
    }

	
    public Product(int barcode, String name, double sellPrice) {
        this.barcode = barcode;
        this.name = name;
        this.sellPrice = sellPrice;
    }
    public Product(int barcode, String name, String description, double sellPrice, Set invoices) {
       this.barcode = barcode;
       this.name = name;
       this.description = description;
       this.sellPrice = sellPrice;
       this.invoices = invoices;
    }
   
    public int getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(int barcode) {
        this.barcode = barcode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(double sellPrice) {
        this.sellPrice = sellPrice;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }

    @Override
    public String toString() {
        return "Product{" + "barcode=" + barcode + ", name=" + name + ", description=" + description + ", sellPrice=" + sellPrice;
    }




}


