/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import javax.swing.table.DefaultTableModel;
import model.Client;

/**
 *
 * @author Estudiante
 */
public class ClientModule extends javax.swing.JFrame {

    DefaultTableModel model;
    ClientController clientController;

    /**
     * Creates new form ClientModule
     */
    public ClientModule() {
        initComponents();
        clientController = new ClientController();
        String[] columnNames = new String[]{"ID", "Name", "Number Phone", "Address"};
        model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);
        listClientTable.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        clientIDTxfld = new javax.swing.JTextField();
        clientNumberPhoneTxfld = new javax.swing.JTextField();
        clientNameTxfld = new javax.swing.JTextField();
        clientAddressTxfld = new javax.swing.JTextField();
        clientesRegistrados = new javax.swing.JLabel();
        clientID = new javax.swing.JLabel();
        nameClient = new javax.swing.JLabel();
        addressClient = new javax.swing.JLabel();
        numberPhoneClient = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        infoMassageLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listClientTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modulo de Clientes");

        clientIDTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientIDTxfld.setToolTipText("ID Client");
        clientIDTxfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDTxfldActionPerformed(evt);
            }
        });

        clientNumberPhoneTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientNumberPhoneTxfld.setToolTipText("Number Phone client");
        clientNumberPhoneTxfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNumberPhoneTxfldActionPerformed(evt);
            }
        });

        clientNameTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientNameTxfld.setToolTipText("Name client");

        clientAddressTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientAddressTxfld.setToolTipText("Address client");

        clientesRegistrados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientesRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesRegistrados.setText("CLIENTES REGISTRADOS");

        clientID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientID.setText("ID Client:");

        nameClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nameClient.setText("Name Client:");

        addressClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addressClient.setText("Address Client:");

        numberPhoneClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numberPhoneClient.setText("Number Phone Client:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        infoMassageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoMassageLbl.setText("-");

        listClientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Number Phone", "Address"
            }
        ));
        listClientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listClientTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listClientTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoMassageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameClient, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clientID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numberPhoneClient, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addressClient, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientNameTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientIDTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientNumberPhoneTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientAddressTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))
                    .addComponent(clientesRegistrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIDTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameClient))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberPhoneClient)
                    .addComponent(clientNumberPhoneTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddressTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressClient))
                .addGap(33, 33, 33)
                .addComponent(saveBtn)
                .addGap(18, 18, 18)
                .addComponent(infoMassageLbl)
                .addGap(28, 28, 28)
                .addComponent(clientesRegistrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientIDTxfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDTxfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDTxfldActionPerformed

    private void clientNumberPhoneTxfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNumberPhoneTxfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNumberPhoneTxfldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String[] params = new String[4];
        params[Client.ID] = clientIDTxfld.getText();
        params[Client.NAME] = clientNameTxfld.getText();
        params[Client.PHONENUMBER] = clientNumberPhoneTxfld.getText();
        params[Client.ADDRESS] = clientAddressTxfld.getText();
        if (clientController.create(params)) {
            refreshClientTable();
            infoMassageLbl.setText("Guardado Correctamente");
        } else {
            infoMassageLbl.setText("Ah ocurrido un error");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void listClientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listClientTableMouseClicked
        listClientTable.getValueAt(listClientTable.getSelectedRow(), listClientTable.getSelectedColumn());
        
        clientController.getClients().get(listClientTable.getSelectedRow());
    }//GEN-LAST:event_listClientTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientModule().setVisible(true);
            }
        });
    }

    private void refreshClientTable() {
        try {
            model.setRowCount(0);
            for (Client currentClient : clientController.getClients()) {
                model.addRow(new Object[]{
                    currentClient.getId(),
                    currentClient.getName(),
                    currentClient.getPhoneNumber(),
                    currentClient.getAddress()
                });
            }
        } catch (Exception e) {
            infoMassageLbl.setText("Error: "+e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressClient;
    private javax.swing.JTextField clientAddressTxfld;
    private javax.swing.JLabel clientID;
    private javax.swing.JTextField clientIDTxfld;
    private javax.swing.JTextField clientNameTxfld;
    private javax.swing.JTextField clientNumberPhoneTxfld;
    private javax.swing.JLabel clientesRegistrados;
    private javax.swing.JLabel infoMassageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listClientTable;
    private javax.swing.JLabel nameClient;
    private javax.swing.JLabel numberPhoneClient;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
