/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InvoiceController;
import javax.swing.table.DefaultTableModel;
import model.Invoice;

/**
 *
 * @author David Ferrer
 */
public class InvoiceClient extends javax.swing.JFrame {

    DefaultTableModel model;
    InvoiceController invoiceController;
    boolean updateFlag;
    int tablePos;
    /**
     * Creates new form InvoiceClient
     */
    public InvoiceClient() {
        initComponents();
        invoiceController = new InvoiceController();
        String[] columnNames = new String[]{"ID", "Date", "Total Price", "Clients"};
        model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);
        listInvoiceTable.setModel(model);
        updateFlag = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalPrice = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        infoMassageLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listInvoiceTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        txtTotalPrice = new javax.swing.JTextField();
        txtInvoiceDate = new javax.swing.JTextField();
        clientesRegistrados = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        invoiceDate = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        cbxClients = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPrice.setText("Total Price:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        infoMassageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoMassageLbl.setText("-");

        listInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Total Price", "Client"
            }
        ));
        listInvoiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listInvoiceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listInvoiceTable);

        btnDelete.setText("Delete");
        btnDelete.setToolTipText("");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modulo de Tiquetes");

        txtInvoiceID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInvoiceID.setToolTipText("ID Client");
        txtInvoiceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceIDActionPerformed(evt);
            }
        });

        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotalPrice.setToolTipText("Number Phone client");
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });

        txtInvoiceDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInvoiceDate.setToolTipText("Name client");

        clientesRegistrados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientesRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesRegistrados.setText("Facturas REGISTRADAS");

        ID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ID.setText("ID Invoice:");

        invoiceDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        invoiceDate.setText("Invoice Date:");

        client.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        client.setText("Client:");

        cbxClients.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoMassageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientesRegistrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(client, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInvoiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(cbxClients, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPrice)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(client)
                    .addComponent(cbxClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(infoMassageLbl)
                .addGap(28, 28, 28)
                .addComponent(clientesRegistrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String[] params = new String[4];
        params[Invoice.ID] = txtInvoiceID.getText();
        params[Invoice.INVOICEDATE] = txtInvoiceDate.getText();
        params[Invoice.TOTALPRICE] = txtTotalPrice.getText();
       // params[Invoice.CLIENT] = clientAddressTxfld.getText();

        if (updateFlag) {
            invoiceController.getInvoices().get(tablePos).setId(Integer.parseInt(params[Invoice.ID]));
            refreshInvoiceTable();
        } else {

            if (invoiceController.create(params)) {
                refreshInvoiceTable();
                infoMassageLbl.setText("Guardado Correctamente");
            } else {
                infoMassageLbl.setText("Ah ocurrido un error");
            }
        }
        clearForm();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void listInvoiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listInvoiceTableMouseClicked
        listInvoiceTable.getValueAt(listInvoiceTable.getSelectedRow(), listInvoiceTable.getSelectedColumn());
        txtInvoiceID.setText(String.valueOf(invoiceController.getInvoices().get(listInvoiceTable.getSelectedRow()).getId()));
        txtInvoiceDate.setText(invoiceController.getInvoices().get(listInvoiceTable.getSelectedRow()).getInvoiceDate());
        txtTotalPrice.setText(String.valueOf(invoiceController.getInvoices().get(listInvoiceTable.getSelectedRow()).getTotalPrice()));
      //  clientAddressTxfld.setText(invoiceController.getClients().get(listInvoiceTable.getSelectedRow()).getAddress());
        updateFlag = true;
        tablePos = listInvoiceTable.getSelectedRow();
        saveBtn.setText("Modificar");
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_listInvoiceTableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (invoiceController.delete(tablePos)) {
            refreshInvoiceTable();
            clearForm();
            infoMassageLbl.setText("Se ha eliminado el usuario correctamente");
        } else {
            infoMassageLbl.setText("Ha ocurrido un error (Error : N14), por favor informa al soporte");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtInvoiceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceIDActionPerformed

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceClient().setVisible(true);
            }
        });
    }

    private void clearForm() {
        txtInvoiceID.setText("");
        txtInvoiceDate.setText("");
        txtTotalPrice.setText("");
        saveBtn.setText("Guardar");
        updateFlag = false;
        tablePos = -1;
        btnDelete.setEnabled(false);
    }
    
    private void refreshInvoiceTable() {
        try {
            model.setRowCount(0);
            for (Invoice currentInvoice : invoiceController.getInvoices()) {
                model.addRow(new Object[]{
                    currentInvoice.getId(),
                    currentInvoice.getInvoiceDate(),
                    currentInvoice.getTotalPrice(),
                    currentInvoice.getClient()
                });
            }
        } catch (Exception e) {
            infoMassageLbl.setText("Error: " + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbxClients;
    private javax.swing.JLabel client;
    private javax.swing.JLabel clientesRegistrados;
    private javax.swing.JLabel infoMassageLbl;
    private javax.swing.JLabel invoiceDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listInvoiceTable;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JTextField txtInvoiceDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
