/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.mainController;
import javax.swing.JOptionPane;

/**
 *
 * @author David Ferrer
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosPnl = new javax.swing.JPanel();
        datosLbl = new javax.swing.JLabel();
        clientID = new javax.swing.JLabel();
        clientIDTxfld = new javax.swing.JTextField();
        nameClient = new javax.swing.JLabel();
        numberPhoneClient = new javax.swing.JLabel();
        addressClient = new javax.swing.JLabel();
        clientAddressTxfld = new javax.swing.JTextField();
        clientNumberPhoneTxfld = new javax.swing.JTextField();
        clientNameTxfld = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        listarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        OKBtn = new javax.swing.JButton();
        elminarBtn = new javax.swing.JButton();
        detallesPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTable = new javax.swing.JTable();
        tituloLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datosPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos - Operaciones"));

        datosLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        datosLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosLbl.setText("Formulario de Datos");

        clientID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        clientID.setText("ID Cliente:");

        clientIDTxfld.setEditable(false);
        clientIDTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientIDTxfld.setToolTipText("ID Client");
        clientIDTxfld.setEnabled(false);
        clientIDTxfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDTxfldActionPerformed(evt);
            }
        });

        nameClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameClient.setText("Nombre Cliente:");

        numberPhoneClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numberPhoneClient.setText("Numero Celular Cliente:");

        addressClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addressClient.setText("Dirección Cliente:");

        clientAddressTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientAddressTxfld.setToolTipText("Address client");

        clientNumberPhoneTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientNumberPhoneTxfld.setToolTipText("Number Phone client");
        clientNumberPhoneTxfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNumberPhoneTxfldActionPerformed(evt);
            }
        });

        clientNameTxfld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientNameTxfld.setToolTipText("Name client");

        guardarBtn.setText("Guardar");

        listarBtn.setText("Listar");

        editarBtn.setText("Editar");

        OKBtn.setText("OK");

        elminarBtn.setText("Eliminar");

        javax.swing.GroupLayout datosPnlLayout = new javax.swing.GroupLayout(datosPnl);
        datosPnl.setLayout(datosPnlLayout);
        datosPnlLayout.setHorizontalGroup(
            datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPnlLayout.createSequentialGroup()
                        .addComponent(datosLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(datosPnlLayout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(listarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(OKBtn)
                        .addGap(18, 18, 18)
                        .addComponent(elminarBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPnlLayout.createSequentialGroup()
                        .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameClient)
                            .addComponent(clientID)
                            .addComponent(numberPhoneClient)
                            .addGroup(datosPnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressClient)))
                        .addGap(75, 75, 75)
                        .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(clientNumberPhoneTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientNameTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientIDTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clientAddressTxfld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        datosPnlLayout.setVerticalGroup(
            datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosLbl)
                .addGap(18, 18, 18)
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIDTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientID))
                .addGap(18, 18, 18)
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameClient))
                .addGap(18, 18, 18)
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNumberPhoneTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberPhoneClient))
                .addGap(18, 18, 18)
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAddressTxfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressClient))
                .addGap(28, 28, 28)
                .addGroup(datosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(listarBtn)
                    .addComponent(editarBtn)
                    .addComponent(OKBtn)
                    .addComponent(elminarBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        detallesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        listaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Numero_Celular", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(listaTable);
        if (listaTable.getColumnModel().getColumnCount() > 0) {
            listaTable.getColumnModel().getColumn(0).setMinWidth(50);
            listaTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            listaTable.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout detallesPnlLayout = new javax.swing.GroupLayout(detallesPnl);
        detallesPnl.setLayout(detallesPnlLayout);
        detallesPnlLayout.setHorizontalGroup(
            detallesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detallesPnlLayout.setVerticalGroup(
            detallesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallesPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );

        tituloLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("CRUD - JAVA - MVC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detallesPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datosPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datosPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detallesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientIDTxfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDTxfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDTxfldActionPerformed

    private void clientNumberPhoneTxfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNumberPhoneTxfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNumberPhoneTxfldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        View vista = new View();
        mainController controller = new mainController(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OKBtn;
    private javax.swing.JLabel addressClient;
    public javax.swing.JTextField clientAddressTxfld;
    private javax.swing.JLabel clientID;
    public javax.swing.JTextField clientIDTxfld;
    public javax.swing.JTextField clientNameTxfld;
    public javax.swing.JTextField clientNumberPhoneTxfld;
    private javax.swing.JLabel datosLbl;
    private javax.swing.JPanel datosPnl;
    private javax.swing.JPanel detallesPnl;
    public javax.swing.JButton editarBtn;
    public javax.swing.JButton elminarBtn;
    public javax.swing.JButton guardarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable listaTable;
    public javax.swing.JButton listarBtn;
    private javax.swing.JLabel nameClient;
    private javax.swing.JLabel numberPhoneClient;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
