package pojo;
// Generated 26/04/2020 02:40:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idAddress;
     private Address address;
     private String name;
     private Set persons = new HashSet(0);
     private Set animals = new HashSet(0);
     private Set medicalTreatments = new HashSet(0);
     private Set addresses = new HashSet(0);

    public Address() {
    }

	
    public Address(String name) {
        this.name = name;
    }
    public Address(Address address, String name, Set persons, Set animals, Set medicalTreatments, Set addresses) {
       this.address = address;
       this.name = name;
       this.persons = persons;
       this.animals = animals;
       this.medicalTreatments = medicalTreatments;
       this.addresses = addresses;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }
    public Set getMedicalTreatments() {
        return this.medicalTreatments;
    }
    
    public void setMedicalTreatments(Set medicalTreatments) {
        this.medicalTreatments = medicalTreatments;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


