package pojo;
// Generated 26/04/2020 02:40:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private Animal animal;
     private MedicalTreatment medicalTreatment;
     private Person person;
     private Date expeditionDate;
     private float totalPrice;

    public Invoice() {
    }

    public Invoice(Animal animal, MedicalTreatment medicalTreatment, Person person, Date expeditionDate, float totalPrice) {
       this.animal = animal;
       this.medicalTreatment = medicalTreatment;
       this.person = person;
       this.expeditionDate = expeditionDate;
       this.totalPrice = totalPrice;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public MedicalTreatment getMedicalTreatment() {
        return this.medicalTreatment;
    }
    
    public void setMedicalTreatment(MedicalTreatment medicalTreatment) {
        this.medicalTreatment = medicalTreatment;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Date getExpeditionDate() {
        return this.expeditionDate;
    }
    
    public void setExpeditionDate(Date expeditionDate) {
        this.expeditionDate = expeditionDate;
    }
    public float getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }




}


